name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.1.2
homepage: https://github.com/mmcc007/screenshots

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.0
  yaml: ^3.1.0
  resource: ^2.1.5
  path: ^1.6.2
#  file: ^6.1.2
  archive: ^3.2.1
  platform: ^3.1.0
#  process: ^4.2.4
  meta: ^1.7.0
  intl: ">=0.15.0 <1.0.0"
  tool_base: ^1.9.5
  tool_mobile: ^1.9.5+1
#  tool_mobile:
#    path: ../tool_mobile

#dev_dependencies:
#  test: ^1.16.5
#  test_api: ^0.2.5
#  mockito: ^4.1.0
#  pedantic: ^1.8.0+1
#  quiver: '>=2.0.0 <3.0.0'
#  fake_process_manager: ^0.1.0
#    path: ../fake_process_manager
#  tool_base_test:
#    git: https://github.com/mmcc007/tool_base_test.git
#    path: ../tool_base_test
#  collection: any

dependency_overrides:
#  tool_mobile: ^1.9.5+1
  tool_base: ^1.9.5
  process: ^3.0.9
  file: ^5.0.7
#  intl: ^0.17.0
  platform: ^3.1.0
  archive: ^3.1.6
#  crypto: ^3.0.1
#  args: ^2.3.0
#  analyzer: ">=1.4.0 <3.0.0"
#  convert: ^3.0.0
#  yaml: ^3.1.0

executables:
  screenshots: main